import Head from 'next/head'
import Header from '@/components/Header'
import UnityBuild from '@/components/UnityBuild'


export default function UnityTest() {
    return (
        <>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header fill='#2F2727'/>
        <UnityBuild/>
        </>
    )
}
